import type { Candidate, ContextInput, Lang } from "./schemas";
import {
  confirmedFragmentCorrection,
  fragmentRepairReading,
  repairFragment,
  type FragmentRepair,
} from "./fragmentRepair";
import { completeWords, hasNegation, hasQuestionCue } from "./lexicon";

export const vocabularyCategories = [
  "core",
  "actions",
  "questions",
  "negation",
  "social",
  "feelings",
  "daily",
  "health",
  "identity",
  "repair",
] as const;
export type VocabularyCategory = (typeof vocabularyCategories)[number];
type SpeechAct =
  "request" | "refuse" | "question" | "report" | "repair" | "social";
type Polarity = "positive" | "negative" | "uncertain";
export interface VocabularyEntry {
  id: string;
  category: VocabularyCategory;
  icon: string;
  en: string;
  ta: string;
  enSentence: string;
  taSentence: string;
  aliases: { en: string[]; ta: string[]; tanglish: string[] };
  speechAct: SpeechAct;
  polarity: Polarity;
  objectId?: string;
  nativeReview: "pending";
  templateVersion: "vocabulary-1";
}
const split = (s: string) => s.split("|").filter(Boolean);
function entry(
  id: string,
  category: VocabularyCategory,
  icon: string,
  en: string,
  ta: string,
  enSentence: string,
  taSentence: string,
  enAliases: string,
  taAliases: string,
  tanglish: string,
  speechAct: SpeechAct = "request",
  polarity: Polarity = "positive",
  objectId?: string,
): VocabularyEntry {
  return {
    id,
    category,
    icon,
    en,
    ta,
    enSentence,
    taSentence,
    aliases: {
      en: split(enAliases),
      ta: split(taAliases),
      tanglish: split(tanglish),
    },
    speechAct,
    polarity,
    objectId,
    nativeReview: "pending",
    templateVersion: "vocabulary-1",
  };
}

/** Draft colloquial wording: automated checks are not native-speaker or clinical approval. */
export const vocabularyCatalog: readonly VocabularyEntry[] = [
  entry(
    "core.yes",
    "core",
    "👍",
    "Yes",
    "ஆமா",
    "Yes.",
    "ஆமா.",
    "yes|yeah|correct|that's right",
    "ஆமாம்|ஆம்|சரி",
    "aama|ama|aamam",
    "report",
  ),
  entry(
    "core.no",
    "core",
    "✋",
    "No",
    "இல்ல",
    "No.",
    "இல்ல.",
    "no|nope",
    "இல்லை",
    "illa|illai",
    "refuse",
    "negative",
  ),
  entry(
    "core.unsure",
    "core",
    "🤔",
    "Not sure",
    "தெரியல",
    "I'm not sure.",
    "எனக்கு சரியா தெரியல.",
    "not sure|unsure|uncertain",
    "உறுதியா தெரியல|சரியா தெரியல",
    "theriyala|teriyala|not sure",
    "report",
    "uncertain",
  ),
  entry(
    "core.dont_know",
    "core",
    "🤷",
    "I don't know",
    "எனக்குத் தெரியல",
    "I don't know.",
    "எனக்குத் தெரியல.",
    "don't know|do not know|dunno",
    "எனக்கு தெரியாது|எனக்குத் தெரியாது",
    "enakku theriyala|enaku theriyathu",
    "report",
    "uncertain",
  ),
  entry(
    "core.more",
    "core",
    "➕",
    "More",
    "இன்னும்",
    "I'd like some more.",
    "இன்னும் கொஞ்சம் வேணும்.",
    "more|some more|another",
    "கொஞ்சம் கூட|இன்னும் கொஞ்சம்",
    "innum|konjam kooda",
    "request",
    "positive",
    "more",
  ),
  entry(
    "core.enough",
    "core",
    "✋",
    "Enough",
    "போதும்",
    "That's enough.",
    "இது போதும்.",
    "enough|that's enough|no more",
    "போதும்|இது போதும்",
    "pothum|podhum",
    "refuse",
    "negative",
    "more",
  ),
  entry(
    "core.now",
    "core",
    "⏱️",
    "Now",
    "இப்போ",
    "I'd like to do it now.",
    "இப்போ செய்யணும்.",
    "now|right now",
    "இப்போது|இப்ப",
    "ippo|ippove",
    "request",
    "positive",
    "time",
  ),
  entry(
    "core.later",
    "core",
    "🕰️",
    "Later",
    "அப்புறம்",
    "I'd like to do it later.",
    "அப்புறம் செய்யலாம்.",
    "later|afterwards|not now",
    "பிறகு|அப்புறம்|இப்போ வேண்டாம்",
    "appuram|piragu|apram",
    "request",
    "positive",
    "time",
  ),
  entry(
    "core.this",
    "core",
    "👆",
    "This one",
    "இது",
    "I mean this one.",
    "நான் சொல்றது இது.",
    "this one|this",
    "இது தான்|இதுதான்",
    "ithu|idhu",
    "report",
  ),
  entry(
    "core.other",
    "core",
    "🔄",
    "Something else",
    "வேற ஏதாவது",
    "I mean something else.",
    "வேற ஏதோ சொல்ல வரேன்.",
    "something else|different|other one",
    "வேற ஒண்ணு|வேற ஏதாவது",
    "vera|vera onnu|veru",
    "repair",
  ),

  entry(
    "action.sit",
    "actions",
    "🪑",
    "Sit",
    "உட்கார",
    "I'd like to sit down.",
    "உட்காரணும்.",
    "sit|sit down|chair",
    "உட்கார|உக்கார",
    "utkara|utkaranum|ukkaranum",
    "request",
    "positive",
    "sit",
  ),
  entry(
    "action.stand",
    "actions",
    "🧍",
    "Stand",
    "எழுந்திருக்க",
    "Please help me stand up.",
    "எழுந்திருக்க உதவி பண்ணுங்க.",
    "stand|stand up|get up",
    "எழுந்திருக்க|எழுந்து நிற்க",
    "ezhunthiru|elunthirikanum|nikkanum",
    "request",
    "positive",
    "stand",
  ),
  entry(
    "action.walk",
    "actions",
    "🚶",
    "Walk",
    "நடக்க",
    "I'd like some help to walk.",
    "நடக்க கொஞ்சம் உதவி வேணும்.",
    "walk|walking",
    "நடக்க|நடை",
    "nadakka|nadakanum",
    "request",
    "positive",
    "walk",
  ),
  entry(
    "action.lie_down",
    "actions",
    "🛏️",
    "Lie down",
    "படுக்க",
    "I'd like to lie down.",
    "கொஞ்சம் படுக்கணும்.",
    "lie down|lay down",
    "படுக்க|படுத்துக்க",
    "padukka|padukanum",
    "request",
    "positive",
    "lie_down",
  ),
  entry(
    "action.turn",
    "actions",
    "↔️",
    "Change position",
    "திரும்பி படுக்க",
    "Please help me change position.",
    "திரும்பி படுக்க உதவி பண்ணுங்க.",
    "change position|turn over|reposition",
    "திரும்பி படுக்க|நிலை மாற்ற",
    "thirumbi padukka|thirumba",
    "request",
    "positive",
    "position",
  ),
  entry(
    "action.bring",
    "actions",
    "🤲",
    "Bring it",
    "எடுத்து தர",
    "Please bring it to me.",
    "அதை என்கிட்ட எடுத்து குடுங்க.",
    "bring it|bring that",
    "அதை எடுத்து குடுங்க|எடுத்து தா",
    "eduthu tha|eduthu kudunga",
    "request",
    "positive",
    "bring",
  ),
  entry(
    "action.open",
    "actions",
    "📂",
    "Open it",
    "திறக்க",
    "Please open it.",
    "அதை திறந்து விடுங்க.",
    "open it|open",
    "திறக்க|திறந்து",
    "thirakka|thiranthu",
    "request",
    "positive",
    "open",
  ),
  entry(
    "action.close",
    "actions",
    "📁",
    "Close it",
    "மூட",
    "Please close it.",
    "அதை மூடுங்க.",
    "close it|close|shut",
    "மூட|மூடு",
    "mooda|moodu",
    "request",
    "positive",
    "close",
  ),
  entry(
    "action.read",
    "actions",
    "📖",
    "Read to me",
    "படிச்சு சொல்ல",
    "Please read this to me.",
    "இதை படிச்சு சொல்லுங்க.",
    "read this|read to me|read",
    "படிச்சு சொல்ல|வாசிக்க",
    "padichu sollunga|vasikka",
    "request",
    "positive",
    "read",
  ),
  entry(
    "action.write",
    "actions",
    "✍️",
    "Write it",
    "எழுத",
    "Please write it down.",
    "அதை எழுதிக் காட்டுங்க.",
    "write it|write down|write",
    "எழுத|எழுதிக் காட்டு",
    "ezhuthu|eluthi kaatu",
    "request",
    "positive",
    "write",
  ),
  entry(
    "action.call",
    "actions",
    "📞",
    "Make a call",
    "ஃபோன் பண்ண",
    "I'd like to make a call.",
    "ஃபோன் பண்ணணும்.",
    "call|make a call|phone call",
    "போன் பண்ண|அழைக்க",
    "phone pannanum|call pannanum",
    "request",
    "positive",
    "call",
  ),
  entry(
    "action.listen",
    "actions",
    "👂",
    "Listen to me",
    "நான் சொல்றதை கேளுங்க",
    "Please listen to me.",
    "நான் சொல்றதை கேளுங்க.",
    "listen to me|listen",
    "கேளுங்க|நான் பேசுறதை கேளுங்க",
    "kelunga|naan solratha kelunga",
    "request",
    "positive",
    "listen",
  ),

  entry(
    "question.what",
    "questions",
    "❓",
    "What?",
    "என்ன?",
    "What do you mean?",
    "என்ன சொல்றீங்க?",
    "what|what do you mean",
    "என்ன|என்ன சொல்றீங்க",
    "enna|enna solreenga",
    "question",
  ),
  entry(
    "question.who",
    "questions",
    "👤",
    "Who?",
    "யாரு?",
    "Who is that?",
    "அது யாரு?",
    "who|who is that",
    "யார்|யாரு",
    "yaaru|yaru",
    "question",
  ),
  entry(
    "question.where",
    "questions",
    "📍",
    "Where?",
    "எங்க?",
    "Where is it?",
    "அது எங்க இருக்கு?",
    "where|where is it",
    "எங்கே|எங்க",
    "enga|enge",
    "question",
  ),
  entry(
    "question.when",
    "questions",
    "🕰️",
    "When?",
    "எப்போ?",
    "When will that happen?",
    "அது எப்போ நடக்கும்?",
    "when|what time",
    "எப்போது|எப்போ",
    "eppo|eppothu",
    "question",
  ),
  entry(
    "question.why",
    "questions",
    "🤔",
    "Why?",
    "ஏன்?",
    "Why is that?",
    "அது ஏன்?",
    "why|why is that",
    "ஏன்|எதுக்கு",
    "yen|ethukku",
    "question",
  ),
  entry(
    "question.how",
    "questions",
    "💭",
    "How?",
    "எப்படி?",
    "How do I do that?",
    "அதை எப்படி செய்யணும்?",
    "how|how do i",
    "எப்படி",
    "eppadi|epdi",
    "question",
  ),
  entry(
    "question.cost",
    "questions",
    "💰",
    "How much?",
    "எவ்வளவு?",
    "How much does it cost?",
    "இதுக்கு எவ்வளவு ஆகும்?",
    "cost|price|how much",
    "விலை|எவ்வளவு",
    "evvalavu|evalo|vilai",
    "question",
    "positive",
    "price",
  ),
  entry(
    "question.choice",
    "questions",
    "↔️",
    "Other choices?",
    "வேற வழி?",
    "What other choices do I have?",
    "எனக்கு வேற என்ன வழி இருக்கு?",
    "other choices|other options|alternatives",
    "வேற வழி|வேற தேர்வு",
    "vera vazhi|vera option",
    "question",
    "positive",
    "choice",
  ),

  entry(
    "refuse.water",
    "negation",
    "🥤",
    "No water",
    "தண்ணி வேண்டாம்",
    "I don't want water.",
    "எனக்கு தண்ணி வேண்டாம்.",
    "no water|don't want water|water no",
    "தண்ணி வேண்டாம்|தண்ணீர் வேண்டாம்|தண்ணி வேணாம்",
    "thanni vendam|tanni venam|water vendam",
    "refuse",
    "negative",
    "water",
  ),
  entry(
    "refuse.food",
    "negation",
    "🍽️",
    "No food",
    "சாப்பாடு வேண்டாம்",
    "I don't want food.",
    "எனக்கு சாப்பாடு வேண்டாம்.",
    "no food|don't want food|don't want to eat",
    "சாப்பாடு வேண்டாம்|சாப்பிட வேண்டாம்",
    "saapadu vendam|sapida venam|food vendam",
    "refuse",
    "negative",
    "food",
  ),
  entry(
    "refuse.tea",
    "negation",
    "🍵",
    "No tea",
    "டீ வேண்டாம்",
    "I don't want tea.",
    "எனக்கு டீ வேண்டாம்.",
    "no tea|don't want tea",
    "டீ வேண்டாம்|தேநீர் வேண்டாம்",
    "tea vendam|tea venam",
    "refuse",
    "negative",
    "tea",
  ),
  entry(
    "refuse.coffee",
    "negation",
    "☕",
    "No coffee",
    "காபி வேண்டாம்",
    "I don't want coffee.",
    "எனக்கு காபி வேண்டாம்.",
    "no coffee|don't want coffee",
    "காபி வேண்டாம்|காப்பி வேண்டாம்",
    "coffee vendam|kaapi venam",
    "refuse",
    "negative",
    "coffee",
  ),
  entry(
    "refuse.touch",
    "negation",
    "✋",
    "Don't touch",
    "தொட வேண்டாம்",
    "Please don't touch me.",
    "என்னை தொட வேண்டாம்.",
    "don't touch|do not touch|no touching",
    "தொடாதீங்க|தொட வேண்டாம்",
    "thoda vendam|thodatheenga",
    "refuse",
    "negative",
    "touch",
  ),
  entry(
    "refuse.visit",
    "negation",
    "🚪",
    "No visitors",
    "இப்போ பார்க்க வேண்டாம்",
    "I don't want visitors now.",
    "இப்போ யாரையும் பார்க்க வேண்டாம்.",
    "no visitors|don't want visitors",
    "யாரையும் பார்க்க வேண்டாம்",
    "visitors vendam|yaaraiyum paaka vendam",
    "refuse",
    "negative",
    "visitors",
  ),
  entry(
    "refuse.go",
    "negation",
    "🏠",
    "Don't want to go",
    "போக வேண்டாம்",
    "I don't want to go.",
    "எனக்கு போக வேண்டாம்.",
    "don't want to go|do not want to go|not going",
    "போக வேண்டாம்|போக விருப்பம் இல்லை",
    "poga vendam|poga venam",
    "refuse",
    "negative",
    "go",
  ),
  entry(
    "refuse.stop",
    "negation",
    "🛑",
    "Stop",
    "நிறுத்துங்க",
    "Please stop.",
    "தயவுசெய்து நிறுத்துங்க.",
    "stop|stop that|please stop",
    "நிறுத்து|நிறுத்துங்க",
    "niruthunga|niruthu|stop pannunga",
    "refuse",
    "negative",
    "stop",
  ),

  entry(
    "social.hello",
    "social",
    "👋",
    "Hello",
    "வணக்கம்",
    "Hello!",
    "வணக்கம்!",
    "hello|hi|hey",
    "வணக்கம்",
    "vanakkam|vanakam",
    "social",
  ),
  entry(
    "social.goodbye",
    "social",
    "👋",
    "Goodbye",
    "போயிட்டு வாங்க",
    "See you again.",
    "மறுபடியும் பார்க்கலாம்.",
    "bye|goodbye|see you",
    "போயிட்டு வாங்க|பார்க்கலாம்",
    "poitu vaanga|bye|paarkalam",
    "social",
  ),
  entry(
    "social.thanks",
    "social",
    "🙏",
    "Thank you",
    "நன்றி",
    "Thank you.",
    "நன்றி.",
    "thanks|thank you|thankyou",
    "நன்றி|ரொம்ப நன்றி",
    "nandri|nanri|thanks",
    "social",
  ),
  entry(
    "social.sorry",
    "social",
    "💬",
    "Sorry",
    "மன்னிச்சுக்கோங்க",
    "I'm sorry.",
    "மன்னிச்சுக்கோங்க.",
    "sorry|apologise|apologize",
    "மன்னிக்கவும்|மன்னிச்சுக்கோங்க",
    "mannichukonga|mannikanum",
    "social",
  ),
  entry(
    "social.how_are_you",
    "social",
    "🙂",
    "How are you?",
    "எப்படி இருக்கீங்க?",
    "How are you?",
    "எப்படி இருக்கீங்க?",
    "how are you|how's things",
    "எப்படி இருக்கீங்க|நலமா",
    "eppadi irukeenga|nalama",
    "question",
  ),
  entry(
    "social.glad",
    "social",
    "😊",
    "Glad to see you",
    "பார்த்ததில் சந்தோஷம்",
    "I'm happy to see you.",
    "உங்களை பார்த்ததில் சந்தோஷம்.",
    "glad to see you|happy to see you",
    "பார்த்ததில் சந்தோஷம்",
    "paathathula santhosham",
    "social",
  ),
  entry(
    "social.miss",
    "social",
    "💜",
    "Miss you",
    "உங்க நினைப்பு",
    "I miss you.",
    "உங்களை ரொம்ப நினைக்கிறேன்.",
    "miss you|missing you",
    "உங்க நினைப்பு|உங்களை நினைக்கிறேன்",
    "ungala miss panren|ninaikiren",
    "social",
  ),
  entry(
    "social.love",
    "social",
    "💜",
    "Love you",
    "உங்களை நேசிக்கிறேன்",
    "I love you.",
    "நான் உங்களை நேசிக்கிறேன்.",
    "love you|love",
    "நேசிக்கிறேன்|அன்பு",
    "nesikiren|love you",
    "social",
  ),
  entry(
    "social.joke",
    "social",
    "😄",
    "Just joking",
    "சும்மா சொன்னேன்",
    "I'm only joking.",
    "சும்மா ஜாலியா சொன்னேன்.",
    "joking|just kidding|joke",
    "சும்மா சொன்னேன்|ஜோக்",
    "summa sonnen|joke",
    "social",
  ),
  entry(
    "social.news",
    "social",
    "🗨️",
    "Something to tell",
    "ஒண்ணு சொல்லணும்",
    "I have something to tell you.",
    "உங்ககிட்ட ஒண்ணு சொல்லணும்.",
    "something to tell|tell you something|news",
    "ஒண்ணு சொல்லணும்|சொல்ல இருக்கு",
    "onnu sollanum|solla iruku",
    "social",
  ),
  entry(
    "social.like",
    "social",
    "👍",
    "I like it",
    "பிடிச்சிருக்கு",
    "I like it.",
    "எனக்கு இது பிடிச்சிருக்கு.",
    "like it|i like this",
    "பிடிச்சிருக்கு|பிடிக்கும்",
    "pidichiruku|pidikkum",
    "report",
  ),
  entry(
    "social.dislike",
    "social",
    "👎",
    "Don't like it",
    "பிடிக்கல",
    "I don't like it.",
    "எனக்கு இது பிடிக்கல.",
    "don't like it|dislike|do not like",
    "பிடிக்கல|பிடிக்காது",
    "pidikala|pidikkala|pidikathu",
    "report",
    "negative",
  ),

  entry(
    "feeling.happy",
    "feelings",
    "😊",
    "Happy",
    "சந்தோஷம்",
    "I feel happy.",
    "எனக்கு சந்தோஷமா இருக்கு.",
    "happy|joyful|glad",
    "சந்தோஷம்|மகிழ்ச்சி",
    "santhosham|magizhchi",
    "report",
    "positive",
    "happy",
  ),
  entry(
    "feeling.sad",
    "feelings",
    "😔",
    "Sad",
    "வருத்தம்",
    "I feel sad.",
    "எனக்கு வருத்தமா இருக்கு.",
    "sad|upset|unhappy",
    "வருத்தம்|சோகம்",
    "varutham|sogam",
    "report",
    "positive",
    "sad",
  ),
  entry(
    "feeling.worried",
    "feelings",
    "😟",
    "Worried",
    "கவலை",
    "I feel worried.",
    "எனக்கு கவலையா இருக்கு.",
    "worried|worry|anxious",
    "கவலை|பதட்டம்",
    "kavalai|pathattam",
    "report",
    "positive",
    "worried",
  ),
  entry(
    "feeling.scared",
    "feelings",
    "😨",
    "Scared",
    "பயம்",
    "I feel scared.",
    "எனக்கு பயமா இருக்கு.",
    "scared|afraid|fear",
    "பயம்|பயமா",
    "bayam|payam",
    "report",
    "positive",
    "scared",
  ),
  entry(
    "feeling.angry",
    "feelings",
    "😠",
    "Angry",
    "கோபம்",
    "I feel angry.",
    "எனக்கு கோபமா இருக்கு.",
    "angry|annoyed|frustrated",
    "கோபம்|எரிச்சல்",
    "kobam|kovam|erichal",
    "report",
    "positive",
    "angry",
  ),
  entry(
    "feeling.lonely",
    "feelings",
    "🧍",
    "Lonely",
    "தனிமை",
    "I feel lonely.",
    "எனக்கு தனிமையா இருக்கு.",
    "lonely|alone",
    "தனிமை|தனியா",
    "thanimai|thaniya",
    "report",
    "positive",
    "lonely",
  ),
  entry(
    "feeling.bored",
    "feelings",
    "😐",
    "Bored",
    "போர் அடிக்குது",
    "I feel bored.",
    "எனக்கு போர் அடிக்குது.",
    "bored|boring",
    "போர் அடிக்குது|சலிப்பு",
    "bore adikuthu|bore",
    "report",
    "positive",
    "bored",
  ),
  entry(
    "feeling.tired",
    "feelings",
    "😴",
    "Tired",
    "சோர்வு",
    "I feel tired.",
    "எனக்கு சோர்வா இருக்கு.",
    "tired|exhausted|fatigue",
    "சோர்வு|களைப்பு",
    "sorvu|sorva|kalaippu",
    "report",
    "positive",
    "tired",
  ),
  entry(
    "feeling.calm",
    "feelings",
    "😌",
    "Calm",
    "நிம்மதி",
    "I feel calm.",
    "எனக்கு நிம்மதியா இருக்கு.",
    "calm|peaceful|relaxed",
    "நிம்மதி|அமைதி",
    "nimmathi|amaithi",
    "report",
    "positive",
    "calm",
  ),
  entry(
    "feeling.confused",
    "feelings",
    "🤔",
    "Confused",
    "குழப்பம்",
    "I feel confused.",
    "எனக்கு குழப்பமா இருக்கு.",
    "confused|confusing",
    "குழப்பம்|புரியாம இருக்கு",
    "kuzhappam|kulapam",
    "report",
    "uncertain",
    "confused",
  ),

  entry(
    "daily.water",
    "daily",
    "🥤",
    "Water",
    "தண்ணி",
    "I'd like some water.",
    "எனக்கு தண்ணி வேணும்.",
    "water|drink water|some water",
    "தண்ணி|தண்ணீர்|தண்ணி வேணும்",
    "thanni|tanni|thanneer|water venum",
    "request",
    "positive",
    "water",
  ),
  entry(
    "daily.tea",
    "daily",
    "🍵",
    "Tea",
    "டீ",
    "I'd like some tea.",
    "எனக்கு டீ வேணும்.",
    "tea|some tea",
    "டீ|தேநீர்",
    "tea|tee|tea venum",
    "request",
    "positive",
    "tea",
  ),
  entry(
    "daily.coffee",
    "daily",
    "☕",
    "Coffee",
    "காபி",
    "I'd like some coffee.",
    "எனக்கு காபி வேணும்.",
    "coffee|some coffee",
    "காபி|காப்பி",
    "kaapi|kapi|coffee venum",
    "request",
    "positive",
    "coffee",
  ),
  entry(
    "daily.milk",
    "daily",
    "🥛",
    "Milk",
    "பால்",
    "I'd like some milk.",
    "எனக்கு பால் வேணும்.",
    "milk|some milk",
    "பால்|பாலு",
    "paal|pal|milk venum",
    "request",
    "positive",
    "milk",
  ),
  entry(
    "daily.bottle",
    "daily",
    "🧴",
    "Bottle",
    "பாட்டில்",
    "Please bring the bottle.",
    "பாட்டிலை எடுத்து குடுங்க.",
    "bottle|bring bottle",
    "பாட்டில்|புட்டி",
    "bottle|paattil",
    "request",
    "positive",
    "bottle",
  ),
  entry(
    "daily.food",
    "daily",
    "🍽️",
    "Food",
    "சாப்பாடு",
    "I'd like something to eat.",
    "எனக்கு சாப்பிட ஏதாவது வேணும்.",
    "food|eat|meal",
    "சாப்பாடு|சாப்பிட|உணவு",
    "saapadu|sapadu|saapida|sapida",
    "request",
    "positive",
    "food",
  ),
  entry(
    "daily.rice",
    "daily",
    "🍚",
    "Rice",
    "சாதம்",
    "I'd like some rice.",
    "எனக்கு கொஞ்சம் சாதம் வேணும்.",
    "rice|some rice",
    "சாதம்|சோறு",
    "saadham|sadam|soru",
    "request",
    "positive",
    "rice",
  ),
  entry(
    "daily.rasam",
    "daily",
    "🥣",
    "Rasam",
    "ரசம்",
    "I'd like some rasam.",
    "எனக்கு ரசம் வேணும்.",
    "rasam",
    "ரசம்",
    "rasam venum",
    "request",
    "positive",
    "rasam",
  ),
  entry(
    "daily.idli",
    "daily",
    "🍽️",
    "Idli",
    "இட்லி",
    "I'd like idli.",
    "எனக்கு இட்லி வேணும்.",
    "idli|idly",
    "இட்லி|இட்லீ",
    "idli|idly",
    "request",
    "positive",
    "idli",
  ),
  entry(
    "daily.dosa",
    "daily",
    "🍽️",
    "Dosa",
    "தோசை",
    "I'd like dosa.",
    "எனக்கு தோசை வேணும்.",
    "dosa|dosai",
    "தோசை|தோச",
    "dosai|dosa|thosai",
    "request",
    "positive",
    "dosa",
  ),
  entry(
    "daily.toilet",
    "daily",
    "🚻",
    "Toilet",
    "பாத்ரூம்",
    "I need to use the toilet.",
    "எனக்கு பாத்ரூம் போகணும்.",
    "toilet|bathroom|loo|restroom",
    "பாத்ரூம்|கழிப்பறை|டாய்லெட்",
    "bathroom|toilet|bathroom poganum",
    "request",
    "positive",
    "toilet",
  ),
  entry(
    "daily.wash",
    "daily",
    "🧼",
    "Wash",
    "கழுவ",
    "I'd like help to wash.",
    "கழுவிக்க உதவி வேணும்.",
    "wash|washing|clean up",
    "கழுவ|கழுவிக்க",
    "kazhuva|kaluva",
    "request",
    "positive",
    "wash",
  ),
  entry(
    "daily.bath",
    "daily",
    "🚿",
    "Bath",
    "குளிக்க",
    "I'd like help to take a bath.",
    "குளிக்க உதவி வேணும்.",
    "bath|shower|bathe",
    "குளிக்க|குளியல்",
    "kulikka|kuliyal",
    "request",
    "positive",
    "bath",
  ),
  entry(
    "daily.clothes",
    "daily",
    "👕",
    "Change clothes",
    "துணி மாத்த",
    "I'd like to change my clothes.",
    "துணி மாத்தணும்.",
    "clothes|change clothes|dress",
    "துணி|உடை|துணி மாத்த",
    "thuni|udai|dress",
    "request",
    "positive",
    "clothes",
  ),
  entry(
    "daily.rest",
    "daily",
    "🛏️",
    "Rest",
    "ஓய்வு",
    "I'd like to rest.",
    "எனக்கு கொஞ்சம் ஓய்வு வேணும்.",
    "rest|take a break|break",
    "ஓய்வு|ஓய்வெடுக்க",
    "oyvu|oivu|rest venum",
    "request",
    "positive",
    "rest",
  ),
  entry(
    "daily.sleep",
    "daily",
    "🌙",
    "Sleep",
    "தூங்க",
    "I'd like to sleep.",
    "எனக்கு தூங்கணும்.",
    "sleep|sleepy|nap",
    "தூங்க|தூக்கம்",
    "thoonga|thookam|tookam",
    "request",
    "positive",
    "sleep",
  ),
  entry(
    "daily.quiet",
    "daily",
    "🔇",
    "Quiet",
    "அமைதியா",
    "I'd like some quiet.",
    "கொஞ்சம் அமைதியா இருக்கணும்.",
    "quiet|too noisy|less noise",
    "சத்தம் வேண்டாம்|அமைதியா",
    "satham vendam|amaithiya",
    "request",
    "positive",
    "quiet",
  ),
  entry(
    "daily.music",
    "daily",
    "🎵",
    "Music",
    "பாட்டு",
    "I'd like to listen to music.",
    "பாட்டு கேக்கணும்.",
    "music|song|songs",
    "பாட்டு|இசை",
    "paatu|paattu|isai",
    "request",
    "positive",
    "music",
  ),
  entry(
    "daily.tv",
    "daily",
    "📺",
    "Television",
    "டிவி",
    "I'd like to watch television.",
    "டிவி பார்க்கணும்.",
    "tv|television|watch tv|turn on tv|turn on the tv",
    "டிவி|தொலைக்காட்சி",
    "tv paakanum|tv",
    "request",
    "positive",
    "tv",
  ),
  entry(
    "daily.phone",
    "daily",
    "📱",
    "My phone",
    "என் ஃபோன்",
    "Please bring my phone.",
    "என் ஃபோனை எடுத்து குடுங்க.",
    "phone|mobile|my phone",
    "ஃபோன்|போன்|கைப்பேசி",
    "phone|mobile|en phone",
    "request",
    "positive",
    "phone",
  ),
  entry(
    "daily.glasses",
    "daily",
    "👓",
    "My glasses",
    "என் கண்ணாடி",
    "Please bring my glasses.",
    "என் கண்ணாடியை எடுத்து குடுங்க.",
    "glasses|spectacles|my glasses",
    "கண்ணாடி|மூக்குக்கண்ணாடி",
    "kannadi|mooku kannadi",
    "request",
    "positive",
    "glasses",
  ),
  entry(
    "daily.blanket",
    "daily",
    "🛏️",
    "Blanket",
    "போர்வை",
    "I'd like a blanket.",
    "எனக்கு போர்வை வேணும்.",
    "blanket|cover",
    "போர்வை",
    "porvai|porva",
    "request",
    "positive",
    "blanket",
  ),
  entry(
    "daily.pillow",
    "daily",
    "🛏️",
    "Pillow",
    "தலையணை",
    "I'd like a pillow.",
    "எனக்கு தலையணை வேணும்.",
    "pillow|cushion",
    "தலையணை",
    "thalayanai|thalagani",
    "request",
    "positive",
    "pillow",
  ),
  entry(
    "daily.fan",
    "daily",
    "🌀",
    "Fan",
    "ஃபேன்",
    "Please turn on the fan.",
    "ஃபேனை போடுங்க.",
    "fan|turn on fan",
    "ஃபேன்|விசிறி",
    "fan podunga|visiri",
    "request",
    "positive",
    "fan",
  ),
  entry(
    "daily.fan_off",
    "daily",
    "🌀",
    "Fan off",
    "ஃபேனை நிறுத்த",
    "Please turn off the fan.",
    "ஃபேனை நிறுத்துங்க.",
    "fan off|turn off fan|switch off fan",
    "ஃபேனை நிறுத்த|ஃபேன் வேண்டாம்",
    "fan off pannunga|fan vendam",
    "request",
    "negative",
    "fan",
  ),
  entry(
    "daily.light",
    "daily",
    "💡",
    "Light",
    "லைட்",
    "Please turn on the light.",
    "லைட்டை போடுங்க.",
    "light|turn on light",
    "லைட்|விளக்கு",
    "light podunga|vilakku",
    "request",
    "positive",
    "light",
  ),
  entry(
    "daily.light_off",
    "daily",
    "💡",
    "Light off",
    "லைட்டை அணைக்க",
    "Please turn off the light.",
    "லைட்டை அணைங்க.",
    "light off|turn off light|switch off light",
    "லைட்டை அணைக்க|லைட் வேண்டாம்",
    "light off pannunga|light vendam",
    "request",
    "negative",
    "light",
  ),
  entry(
    "daily.outside",
    "daily",
    "🌳",
    "Go outside",
    "வெளியே போக",
    "I'd like to go outside.",
    "வெளியே போகணும்.",
    "outside|go outside|fresh air",
    "வெளியே|வெளில",
    "veliye|velila",
    "request",
    "positive",
    "outside",
  ),
  entry(
    "daily.home",
    "daily",
    "🏠",
    "Go home",
    "வீட்டுக்கு போக",
    "I'd like to go home.",
    "வீட்டுக்கு போகணும்.",
    "home|go home",
    "வீடு|வீட்டுக்கு",
    "veedu|veetukku",
    "request",
    "positive",
    "home",
  ),
  entry(
    "daily.pray",
    "daily",
    "🙏",
    "Pray",
    "பிரார்த்தனை",
    "I'd like some time to pray.",
    "பிரார்த்தனை பண்ண நேரம் வேணும்.",
    "pray|prayer|worship",
    "பிரார்த்தனை|வழிபாடு",
    "prarthanai|saami|sami",
    "request",
    "positive",
    "prayer",
  ),

  entry(
    "health.pain",
    "health",
    "🤕",
    "Pain",
    "வலி",
    "I have pain.",
    "எனக்கு வலி இருக்கு.",
    "pain|hurts|hurting|ache",
    "வலி|வலிக்குது",
    "vali|valikuthu|valikkuthu",
    "report",
    "positive",
    "pain",
  ),
  entry(
    "health.no_pain",
    "health",
    "🙂",
    "No pain",
    "வலி இல்ல",
    "I don't have pain.",
    "எனக்கு வலி இல்ல.",
    "no pain|doesn't hurt|not hurting",
    "வலி இல்ல|வலி இல்லை|வலிக்கல",
    "vali illa|valikala|pain illa",
    "report",
    "negative",
    "pain",
  ),
  entry(
    "health.hot",
    "health",
    "🌡️",
    "Feel hot",
    "சூடா இருக்கு",
    "I feel hot.",
    "எனக்கு சூடா இருக்கு.",
    "hot|too warm|feel hot",
    "சூடா|வெயில்",
    "sooda|suda|hot ah",
    "report",
    "positive",
    "hot",
  ),
  entry(
    "health.cold",
    "health",
    "🥶",
    "Feel cold",
    "குளிருது",
    "I feel cold.",
    "எனக்கு குளிருது.",
    "cold|chilly|feel cold",
    "குளிருது|குளிர்",
    "kuliruthu|kuluru",
    "report",
    "positive",
    "cold",
  ),
  entry(
    "health.dizzy",
    "health",
    "😵",
    "Dizzy",
    "தலை சுத்துது",
    "I feel dizzy.",
    "எனக்கு தலை சுத்துது.",
    "dizzy|dizziness|lightheaded",
    "தலை சுத்துது|தலை சுற்றுது",
    "thalai suthuthu|thala suthuthu",
    "report",
    "positive",
    "dizzy",
  ),
  entry(
    "health.nausea",
    "health",
    "🤢",
    "Feel sick",
    "குமட்டுது",
    "I feel like I might vomit.",
    "எனக்கு வாந்தி வர மாதிரி இருக்கு.",
    "nausea|nauseous|feel sick|vomit",
    "குமட்டுது|வாந்தி",
    "kumattuthu|vaanthi|vanthi",
    "report",
    "positive",
    "nausea",
  ),
  entry(
    "health.itch",
    "health",
    "✋",
    "Itchy",
    "அரிக்குது",
    "I feel itchy.",
    "எனக்கு அரிக்குது.",
    "itch|itchy|itching",
    "அரிக்குது|அரிப்பு",
    "arikkuthu|arippu",
    "report",
    "positive",
    "itch",
  ),
  entry(
    "health.uncomfortable",
    "health",
    "🛏️",
    "Uncomfortable",
    "வசதியா இல்ல",
    "I'm uncomfortable in this position.",
    "இந்த நிலையில் வசதியா இல்ல.",
    "uncomfortable|not comfortable",
    "வசதியா இல்ல|அசௌகரியம்",
    "vasathiya illa|comfortable illa",
    "report",
    "negative",
    "comfort",
  ),
  entry(
    "health.comfortable",
    "health",
    "😌",
    "Comfortable",
    "வசதியா இருக்கு",
    "I'm comfortable now.",
    "இப்போ வசதியா இருக்கு.",
    "comfortable|comfortable now",
    "வசதியா இருக்கு",
    "vasathiya iruku",
    "report",
    "positive",
    "comfort",
  ),
  entry(
    "health.doctor",
    "health",
    "🩺",
    "Speak to doctor",
    "டாக்டரிடம் பேச",
    "I'd like to speak to the doctor.",
    "டாக்டர்கிட்ட பேசணும்.",
    "doctor|speak to doctor",
    "டாக்டர்|மருத்துவர்",
    "doctor|doctorkitta",
    "request",
    "positive",
    "doctor",
  ),
  entry(
    "health.nurse",
    "health",
    "🧑‍⚕️",
    "Call nurse",
    "நர்ஸை கூப்பிட",
    "Please call the nurse.",
    "நர்ஸை கூப்பிடுங்க.",
    "nurse|call nurse",
    "நர்ஸ்|செவிலியர்",
    "nurse|nurse koopidunga",
    "request",
    "positive",
    "nurse",
  ),
  entry(
    "health.explain",
    "health",
    "💬",
    "Explain my care",
    "விளக்கி சொல்ல",
    "Please explain what you are going to do.",
    "என்ன செய்யப் போறீங்கன்னு விளக்கி சொல்லுங்க.",
    "explain procedure|explain treatment|what will you do",
    "என்ன செய்யப் போறீங்க|சிகிச்சை விளக்கம்",
    "enna seyya poreenga",
    "question",
    "positive",
    "care",
  ),
  entry(
    "health.medicine_question",
    "health",
    "💊",
    "Ask about medicine",
    "மருந்து பற்றி கேட்க",
    "I'd like to ask about my medicine.",
    "என் மருந்து பற்றி கேக்கணும்.",
    "medicine question|ask about medicine|tablet question",
    "மருந்து பற்றி|மாத்திரை பற்றி",
    "marunthu pathi|tablet pathi",
    "question",
    "positive",
    "medicine",
  ),
  entry(
    "health.consent_question",
    "health",
    "❓",
    "Need more information",
    "இன்னும் விளக்கம்",
    "I need more information before I decide.",
    "முடிவு பண்ண முன்னாடி இன்னும் விளக்கம் வேணும்.",
    "before i decide|more information|need information",
    "முடிவு பண்ண முன்னாடி|இன்னும் விளக்கம்",
    "innum vilakkam|mudivu panna",
    "question",
    "uncertain",
    "care",
  ),

  entry(
    "identity.my_choice",
    "identity",
    "🙋",
    "My choice",
    "என் முடிவு",
    "I want to make this choice myself.",
    "இந்த முடிவை நானே எடுக்கணும்.",
    "my choice|decide myself|my decision",
    "என் முடிவு|நானே முடிவு",
    "en mudivu|naane mudivu",
    "report",
  ),
  entry(
    "identity.include_me",
    "identity",
    "💬",
    "Include me",
    "என்கிட்டயும் பேசுங்க",
    "Please include me in this conversation.",
    "இந்த பேச்சுல என்னையும் சேர்த்துக்கோங்க.",
    "include me|talk to me|don't talk over me",
    "என்கிட்ட பேசுங்க|என்னையும் சேர்த்து",
    "enkitta pesunga|ennaiyum serthu",
    "request",
  ),
  entry(
    "identity.family",
    "identity",
    "👨‍👩‍👧",
    "My family",
    "என் குடும்பம்",
    "I'd like to see my family.",
    "என் குடும்பத்தினரை பார்க்கணும்.",
    "family|my family",
    "குடும்பம்|என் குடும்பம்",
    "kudumbam|family",
    "request",
    "positive",
    "family",
  ),
  entry(
    "identity.friend",
    "identity",
    "🤝",
    "My friend",
    "என் நண்பர்",
    "I'd like to see my friend.",
    "என் நண்பரை பார்க்கணும்.",
    "friend|my friend",
    "நண்பர்|தோழி|நண்பன்",
    "nanbar|nanban|thozhi",
    "request",
    "positive",
    "friend",
  ),
  entry(
    "identity.privacy",
    "identity",
    "🚪",
    "Some privacy",
    "தனியா இருக்க",
    "I'd like some privacy.",
    "எனக்கு கொஞ்சம் தனிமை வேணும்.",
    "privacy|private|alone time",
    "தனியா இருக்கணும்|தனிமை வேணும்",
    "thaniya irukkanum|privacy",
    "request",
    "positive",
    "privacy",
  ),
  entry(
    "identity.tamil",
    "identity",
    "💬",
    "Speak Tamil",
    "தமிழ்ல பேசுங்க",
    "Please speak Tamil with me.",
    "என்கிட்ட தமிழ்ல பேசுங்க.",
    "speak tamil|tamil please|tamil",
    "தமிழ்|தமிழ்ல பேசுங்க",
    "tamil la pesunga|thamizh",
    "request",
    "positive",
    "language",
  ),
  entry(
    "identity.english",
    "identity",
    "💬",
    "Speak English",
    "ஆங்கிலத்தில் பேசுங்க",
    "Please speak English with me.",
    "என்கிட்ட ஆங்கிலத்தில் பேசுங்க.",
    "speak english|english please|english",
    "ஆங்கிலம்|இங்கிலீஷ்",
    "english la pesunga|aangilam",
    "request",
    "positive",
    "language",
  ),
  entry(
    "identity.story",
    "identity",
    "📖",
    "My story",
    "என் கதை",
    "I'd like to tell you about myself.",
    "என்னைப் பற்றி சொல்லணும்.",
    "my story|about myself|about me",
    "என்னைப் பற்றி|என் கதை",
    "ennai pathi|en kathai",
    "social",
  ),

  entry(
    "repair.time",
    "repair",
    "⏳",
    "Give me time",
    "நேரம் குடுங்க",
    "Please give me time to speak.",
    "பேச கொஞ்சம் நேரம் குடுங்க.",
    "give me time|time to speak|wait for me",
    "நேரம் குடுங்க|பேச நேரம்",
    "neram kudunga|time kudunga",
    "repair",
  ),
  entry(
    "repair.repeat",
    "repair",
    "🔁",
    "Say it again",
    "மறுபடியும் சொல்லுங்க",
    "Please say that again.",
    "அதை மறுபடியும் சொல்லுங்க.",
    "repeat|say again|again please",
    "மறுபடியும் சொல்லுங்க|திரும்ப சொல்லுங்க",
    "marupadi sollunga|thirumba sollunga",
    "repair",
  ),
  entry(
    "repair.slower",
    "repair",
    "🐢",
    "Speak slowly",
    "மெதுவா பேசுங்க",
    "Please speak more slowly.",
    "கொஞ்சம் மெதுவா பேசுங்க.",
    "speak slowly|slower|slow down",
    "மெதுவா பேசுங்க|மெதுவா",
    "methuva pesunga|medhuva",
    "repair",
  ),
  entry(
    "repair.one_question",
    "repair",
    "❓",
    "One question at a time",
    "ஒரு கேள்வி",
    "Please ask one question at a time.",
    "ஒரு நேரத்துல ஒரு கேள்வி கேளுங்க.",
    "one question at a time|one question",
    "ஒரு கேள்வி|ஒவ்வொரு கேள்வியா",
    "oru kelvi|one question",
    "repair",
  ),
  entry(
    "repair.wrong",
    "repair",
    "↩️",
    "Not what I meant",
    "அப்படி சொல்லல",
    "That's not what I meant.",
    "நான் அப்படி சொல்ல வரல.",
    "not what i meant|wrong meaning|wrong word",
    "அப்படி சொல்லல|அந்த வார்த்தை இல்ல",
    "apdi sollala|antha vaarthai illa",
    "repair",
    "negative",
  ),
  entry(
    "repair.understand",
    "repair",
    "👍",
    "I understand",
    "புரியுது",
    "I understand.",
    "எனக்கு புரியுது.",
    "i understand|understood|got it",
    "புரியுது|புரிஞ்சுது",
    "puriyuthu|purinjuthu",
    "report",
  ),
  entry(
    "repair.dont_understand",
    "repair",
    "🤔",
    "Don't understand",
    "புரியல",
    "I don't understand.",
    "எனக்கு புரியல.",
    "don't understand|do not understand|not understand",
    "புரியல|புரியவில்லை",
    "puriyala|puriyavillai",
    "repair",
    "negative",
  ),
  entry(
    "repair.changed_mind",
    "repair",
    "🔄",
    "Changed my mind",
    "மனசை மாத்திட்டேன்",
    "I've changed my mind.",
    "என் மனசை மாத்திட்டேன்.",
    "changed my mind|change my mind",
    "மனசை மாத்திட்டேன்|முடிவை மாத்திட்டேன்",
    "manasa maathiten|mudiva maathiten",
    "repair",
  ),
  entry(
    "repair.show",
    "repair",
    "👆",
    "I'll show you",
    "காட்டுறேன்",
    "I'll show you what I mean.",
    "நான் என்ன சொல்றேன்னு காட்டுறேன்.",
    "show you|i will show|point to it",
    "காட்டுறேன்|காட்டி சொல்றேன்",
    "kaaturen|kaati solren",
    "repair",
  ),
  entry(
    "repair.help_words",
    "repair",
    "🗨️",
    "Help with words",
    "வார்த்தைக்கு உதவி",
    "Please help me find the word.",
    "வார்த்தையை கண்டுபிடிக்க உதவி பண்ணுங்க.",
    "find the word|help with words|word help",
    "வார்த்தைக்கு உதவி|வார்த்தை வரல",
    "vaarthai varala|word help",
    "repair",
  ),
  entry(
    "repair.finish",
    "repair",
    "✋",
    "Let me finish",
    "பேசி முடிக்க விடுங்க",
    "Please let me finish speaking.",
    "நான் பேசி முடிக்க விடுங்க.",
    "let me finish|don't interrupt",
    "பேசி முடிக்க விடுங்க|குறுக்க பேசாதீங்க",
    "pesi mudikka vidunga",
    "repair",
  ),
  entry(
    "repair.pause",
    "repair",
    "⏸️",
    "Pause this conversation",
    "கொஞ்சம் நிறுத்தலாம்",
    "I'd like to pause this conversation.",
    "இந்த பேச்சை கொஞ்சம் நிறுத்தலாம்.",
    "pause conversation|pause talking|need a pause",
    "பேச்சை நிறுத்தலாம்|கொஞ்சம் நிறுத்தலாம்",
    "pechai niruthalam|pause",
    "repair",
  ),
];

export function normalizeVocabularyQuery(value: string): string {
  return value
    .normalize("NFC")
    .toLowerCase()
    .replace(/[’‘]/g, "'")
    .replace(/[^\p{L}\p{M}\p{N}'\s]/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}
const catalogTokens = new Set(
  [
    ...vocabularyCatalog.flatMap((v) => [
      v.en,
      v.ta,
      v.enSentence,
      v.taSentence,
      ...v.aliases.en,
      ...v.aliases.ta,
      ...v.aliases.tanglish,
    ]),
    // Complete everyday/health/body words are known, so they are never "completed".
    ...completeWords,
  ].flatMap((form) => normalizeVocabularyQuery(form).split(" ")),
);
const repairableTokens = new Set(
  vocabularyCatalog
    .filter((v) => v.category !== "health" && v.polarity === "positive")
    .flatMap((v) => [...v.aliases.en, ...v.aliases.ta, ...v.aliases.tanglish])
    .map(normalizeVocabularyQuery)
    .filter((form) => /^[\p{L}\p{M}]+$/u.test(form)),
);

/** Original text must still be retained for display, evidence and any model request. */
export function repairCatalogFragment(raw: string): FragmentRepair {
  return repairFragment(raw, {
    repairable: repairableTokens,
    known: catalogTokens,
  });
}

export function prepareCatalogFragment(context: ContextInput): {
  text: string;
  reading?: string;
  ambiguous: boolean;
} {
  const confirmed = confirmedFragmentCorrection(context);
  if (confirmed.ambiguous) return confirmed;
  const repaired = repairCatalogFragment(confirmed.text);
  return {
    text: repaired.text,
    reading: confirmed.reading ?? fragmentRepairReading(repaired),
    ambiguous: false,
  };
}
const forms = (v: VocabularyEntry) =>
  [
    v.id,
    v.en,
    v.ta,
    v.enSentence,
    v.taSentence,
    ...v.aliases.en,
    ...v.aliases.ta,
    ...v.aliases.tanglish,
  ].map(normalizeVocabularyQuery);
function containsPhrase(text: string, phrase: string): boolean {
  return ` ${text} `.includes(` ${phrase} `);
}
/** Code points, not UTF-16 units. A whole Tamil-script word matched on token boundaries is
 * distinctive even when it is one syllable (டீ), unlike a short Latin token (hi, tv). */
const formSize = (form: string) =>
  Math.max([...form].length, /^[\p{Script=Tamil}\s]+$/u.test(form) ? 3 : 0);
function score(v: VocabularyEntry, query: string): number {
  const all = forms(v);
  if (all.includes(query)) return 100;
  const matched = all.filter(
    (form) => formSize(form) >= 3 && containsPhrase(query, form),
  );
  if (matched.length)
    return Math.max(...matched.map((form) => 20 + formSize(form)));
  return all.some((form) => form.startsWith(query)) ? 5 : 0;
}
export function searchVocabulary(
  query: string,
  options: { lang?: Lang; category?: VocabularyCategory; limit?: number } = {},
): VocabularyEntry[] {
  const normalized = normalizeVocabularyQuery(query);
  return vocabularyCatalog
    .filter((v) => !options.category || v.category === options.category)
    .map((v, order) => ({
      v,
      order,
      score: normalized ? score(v, normalized) : 1,
    }))
    .filter((v) => v.score > 0)
    .sort((a, b) => b.score - a.score || a.order - b.order)
    .slice(
      0,
      Math.max(0, Math.min(options.limit ?? 30, vocabularyCatalog.length)),
    )
    .map(({ v }) => v);
}
export function getVocabularyCandidate(
  id: string,
  lang: Lang,
): Candidate | undefined {
  const v = vocabularyCatalog.find((item) => item.id === id);
  if (!v) return undefined;
  const text = lang === "ta" ? v.taSentence : v.enSentence;
  return {
    text,
    gloss_en: v.enSentence,
    intent: v.id,
    intentId: v.id,
    icon: v.icon,
    reading: v.en.slice(0, 40),
    keyword: lang === "ta" ? v.ta : v.en,
    urgency: "none",
    lang,
    speechAct: v.speechAct,
    polarity: v.polarity,
    objectId: v.objectId,
    timeScope: "unspecified",
    evidenceRefs: [`catalog:${v.id}`],
    templateVersion: v.templateVersion,
    source: "catalog",
  };
}

// Grammar already present in authored request wording; these do not change the meaning.
const benignTamilTokens = new Set([
  "எனக்கு",
  "கொஞ்சம்",
  "வேணும்",
  "வேண்டும்",
  "ப்ளீஸ்",
  "தயவுசெய்து",
  "குடுங்க",
  "கொடுங்க",
]);
/** Tamil-script tokens not found in the authored Tamil wording of any given entry. */
export function unexplainedTamilTokens(
  text: string,
  entries: readonly VocabularyEntry[],
): string[] {
  const supported = new Set(
    entries
      .flatMap((v) => [v.ta, v.taSentence, ...v.aliases.ta])
      .flatMap((form) => normalizeVocabularyQuery(form).split(" ")),
  );
  return (normalizeVocabularyQuery(text).match(/[\p{L}\p{M}]+/gu) ?? []).filter(
    (token) =>
      /\p{Script=Tamil}/u.test(token) &&
      !supported.has(token) &&
      !benignTamilTokens.has(token),
  );
}

/** Conservative exact/alias retrieval. New sentences, body slots and personalised facts are not invented. */
export function getVocabularyCandidates(context: ContextInput): Candidate[] {
  const prepared = prepareCatalogFragment(context);
  if (prepared.ambiguous) return [];
  let raw = normalizeVocabularyQuery(prepared.text);
  if (
    context.fragment.modality === "topic" &&
    (context.fragment.topicPath?.length ?? 0) > 1
  ) {
    const parents = new Set(
      context.fragment.topicPath!.slice(0, -1).map(normalizeVocabularyQuery),
    );
    raw = raw
      .split(" ")
      .filter((token) => !parents.has(token))
      .join(" ");
  }
  const lang = context.outputLang ?? context.lang ?? "ta";
  const excluded = new Set(
    (context.exclude ?? []).map(normalizeVocabularyQuery),
  );
  const exact = vocabularyCatalog.filter((v) => forms(v).includes(raw));
  if (
    !exact.length &&
    /\b(?:but|except|instead|rather|unless)\b|ஆனா|ஆனால்|தவிர/u.test(raw)
  )
    return [];
  let matches = exact.length
    ? exact
    : searchVocabulary(raw, { limit: 12 }).filter((v) => score(v, raw) >= 23);
  // Prefer an explicit multiword phrase over a contained noun or generic yes/no word.
  if (exact.length) matches = exact;
  else {
    const negative = hasNegation(raw) || /\boff\b/u.test(raw);
    if (negative) matches = matches.filter((v) => v.polarity !== "positive");
    const question = hasQuestionCue(raw);
    if (question) matches = matches.filter((v) => v.speechAct === "question");
    // A location, number, named person or different body part needs a dedicated renderer.
    if (
      /\p{N}|\b(?:left|right|yesterday|tomorrow|already|mg|ml)\b|இடது|வலது|நேற்று|நாளை/u.test(
        raw,
      )
    )
      return [];
    // An unexplained Tamil tense, negation, question or other qualifier (சாப்பிடல, குடிச்சேன்,
    // வந்தாரா) must not disappear into a generic positive card. Ask instead.
    if (unexplainedTamilTokens(raw, matches).length) return [];
    const objectIds = new Set(matches.map((v) => v.objectId).filter(Boolean));
    if (objectIds.size > 1) return [];
  }
  const seen = new Set<string>();
  return matches
    .flatMap((v) => {
      const candidate = getVocabularyCandidate(v.id, lang)!;
      if (
        excluded.has(normalizeVocabularyQuery(candidate.text)) ||
        seen.has(v.id)
      )
        return [];
      seen.add(v.id);
      return [{ ...candidate, reading: prepared.reading ?? candidate.reading }];
    })
    .slice(0, 3);
}
